name: deploying the java project actions on EC2
on: workflow_dispatch
jobs:
  deploy-on-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code from the repository
        uses: actions/checkout@v4

      # - name: Configure AWS credentials
      #   id: creds
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }} 
      #     output-credentials: true  # Optional, depending on your use case

      # - name: Add SSH key
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Your SSH private key stored in secrets


      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Your SSH private key stored in secrets

      # - name: Add SSH key to Agent
      #   run: |
      #     eval "$(ssh-agent -s)"
      #     ssh-add - <<< "${{ secrets.EC2_SSH_KEY }}"
      
      - name: Connect to EC2 instance and install OpenJDK 17
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          # Update package list
          sudo apt update

          # Install OpenJDK 17
          sudo apt install openjdk-17-jdk -y

          # Set Java 17 as default
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

          # Verify Java installation
          java -version
          javac -version
          
          # Install Maven 3.8.7
          wget https://dlcdn.apache.org/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.tar.gz
          sudo tar xzvf apache-maven-3.8.7-bin.tar.gz -C /opt
          sudo ln -s /opt/apache-maven-3.8.7 /opt/maven
          
          # Install Maven (latest version from the repository)
          sudo apt install maven -y

          # Verify Maven installation
          mvn -version

      - name: Connect to EC2 instance and set up the project
        run: |
         ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          # Update package list and install Git
          sudo apt update -y
          sudo apt install git -y
          
          # Add GitHub to known hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Test SSH connection to GitHub
          ssh -T git@github.com || true  # Ignore failure for testing connection
          
          # Clone the project if it doesn't exist
          if [ ! -d "java-demo-project" ]; then
            git clone git@github.com:surajchauhan2310/java-demo-project.git
          fi
          
          # Navigate to the project directory
          cd java-demo-project

     

      - name: Clean using Maven command
        run: |
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} 'pwd'
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} 'ls -la' 
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} 'cd java-demo-project' 
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} 'ls -la' 


      #     ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} 'cd /home/ubuntu/ && mvn clean'

      # - name: Build the package using Maven command
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} 'cd /home/ubuntu/ && mvn package'

      # - name: Run the app
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} 'cd /home/ubuntu/ && java -jar your-app.jar'
      #   #  java -jar target/
        









































